platform :ios, '5.0'
pod 'AFNetworking', '1.0'
pod 'MBProgressHUD', '0.5'
pod 'AdMob', '~>6.2'
pod 'AFUrbanAirshipClient'
pod 'EDColor', '0.2'
pod 'FlurrySDK', '4.1'
pod 'MKStoreKit', '4.99'
pod 'TestFlightSDK', '~> 1.2'
